/*!
 * engine-tips.js — Explainer popups T1–T7 (EXPLAINER-POPUPS-SPEC.md)
 * Click/tap only · one open · Esc / outside / × / Got it · session dismiss optional
 * ART OFF · dollar-free · cream/charcoal/rust/gold via page tokens when CSS present
 * Tip trigger: Ask Odin (pixel rabbit mark) — not "?"
 */
(function () {
  "use strict";
  if (document.getElementById("c3i-tip-css")) return;
  var STYLE = [
    ".c3i-tip-wrap{position:relative;display:inline-flex;align-items:center;gap:.28rem;vertical-align:middle;margin-left:.65rem;flex-shrink:0;opacity:1}",
    ".c3i-tip-btn{display:inline-flex;align-items:center;justify-content:center;gap:.28rem;width:auto;height:auto;min-width:44px;min-height:44px;margin:-.4rem -.15rem;padding:.2rem .45rem .2rem .2rem;border:1px solid rgba(28,31,34,.18);border-radius:999px;background:rgba(255,252,247,.65);color:var(--ink,#121416);font:600 12px/1 var(--font,Inter,system-ui,sans-serif);cursor:pointer;letter-spacing:.02em;text-transform:none;box-sizing:border-box;opacity:1}",
    ".c3i-tip-btn:focus-visible{outline:2px solid var(--accent,#B5512C);outline-offset:2px}",
    ".c3i-tip-btn[aria-expanded=\"true\"]{background:var(--brand,#1C1F22);color:var(--brand-ink,#F7F3EC);border-color:var(--brand,#1C1F22)}",
    ".c3i-tip-btn[aria-expanded=\"true\"] .c3i-tip-btn__face{border-color:rgba(247,243,236,.35)}",
    ".c3i-tip-btn__face{display:block;width:32px;height:32px;border-radius:50%;object-fit:cover;flex-shrink:0;background:#fff;border:1px solid rgba(28,31,34,.12);pointer-events:none;opacity:1;image-rendering:auto}",
    ".c3i-tip-btn__ask{opacity:.92;pointer-events:none;user-select:none;font-size:12px;font-weight:600;letter-spacing:.02em;text-transform:none}",
    ".c3i-tip-btn[aria-expanded=\"true\"] .c3i-tip-btn__ask{opacity:1}",
    ".c3i-tip-panel{position:absolute;z-index:50;left:50%;transform:translateX(-50%);top:calc(100% + .5rem);width:min(280px,calc(100vw - 2rem));max-width:calc(100vw - 1.5rem);max-height:min(70vh,420px);overflow:auto;padding:.85rem 1rem 1rem;border:1px solid var(--line,#D9D0C4);border-radius:10px;background:var(--bg-card,#FFFcf7);color:var(--ink,#121416);box-shadow:var(--shadow,0 8px 28px rgba(18,20,22,.16));font:400 16px/1.45 var(--font,Inter,system-ui,sans-serif);text-align:left;text-transform:none}",
    ".c3i-tip-panel[hidden]{display:none!important;visibility:hidden;pointer-events:none}",
    ".c3i-tip-panel.is-above{top:auto;bottom:calc(100% + .5rem)}",
    ".c3i-tip-panel__title{margin:0 1.75rem .4rem 0;font:600 15px/1.3 var(--font,Inter,sans-serif);color:var(--ink,#121416);text-align:left;text-transform:none}",
    ".c3i-tip-panel__body{margin:0;font-size:16px;line-height:1.45;color:var(--ink,#121416);text-align:left;text-transform:none}",
    ".c3i-tip-panel__x{position:absolute;top:.25rem;right:.15rem;width:44px;height:44px;border:0;background:transparent;color:var(--ink,#121416);font-size:1.35rem;line-height:1;cursor:pointer}",
    ".c3i-tip-panel__ok{display:inline-flex;align-items:center;justify-content:center;margin-top:.7rem;min-height:44px;min-width:5.5rem;border:0;border-radius:8px;padding:.55rem 1rem;background:var(--accent,#B5512C);color:#F7F3EC;font:600 14px/1 var(--font,Inter,sans-serif);cursor:pointer;text-transform:none}",
    ".c3i-tip-panel__ok:focus-visible,.c3i-tip-panel__x:focus-visible{outline:2px solid var(--gold-deep,#A9702B);outline-offset:2px}"
  ].join("");
  var TIPS=[
    {id:"T1",anchor:".hero__eyebrow",label:"Operating Desk",title:"What’s an Operating Desk?",body:"You’re worn thin being the whole office. Your site stays a simple front door; behind it a desk answers and drafts, like front-office help that never books a job or spends money until you say yes."},
    {id:"T2",anchor:".hero__stamp",label:"You approve",title:"Nothing sends until you stamp",body:"The desk can draft texts, emails, and next steps. It does not send them or spend money on its own. You tap approve, like signing a work order before it goes out."},
    {id:"T3",anchor:"#how .step:nth-of-type(1) h3",label:"Audit",title:"We look at what’s live",body:"We read your public website as a customer would: pages, offers, how someone books. That way the desk is grounded in your real business, not a generic script."},
    {id:"T4",anchor:"#how .step:nth-of-type(2) h3",label:"Prove",title:"See it on your URL",body:"We stand up a live desk against your public site so you can try real questions before anything is wired deep. Often you can see this on a live link in minutes."},
    {id:"T5",anchor:"#how .step:nth-of-type(3) h3",label:"Door",title:"A door on your site. You keep the keys",body:"When you’re ready, a simple door on your site opens the desk for visitors. Deeper hooks (mail, calendar, CRM) wait for your OK."},
    {id:"T6",anchor:"#product-title",label:"Operating Desk",title:"Why owners care",body:"Auto-send and auto-spend stay off. Outbound stays draft until you approve. Connectors stay human-approved. You’re still the boss of money and messages."},
    {id:"T7",anchor:"#pricing .price-card:first-of-type .price-card__amount",label:"Ask",title:"Why it says Ask",body:"We don’t put a public price list on this page. First step is paid discovery on your site and one named problem: written scope, hard end, then terms that match that scope."}
  ];
  var style=document.createElement("style");style.id="c3i-tip-css";style.textContent=STYLE;document.head.appendChild(style);
  var openId=null,lastBtn=null;
  function markDismissed(id){try{sessionStorage.setItem("c3i-tip-dismissed-"+id,"1")}catch(e){}}
  function closeAll(opts){opts=opts||{};document.querySelectorAll(".c3i-tip-panel").forEach(function(p){p.hidden=true});document.querySelectorAll(".c3i-tip-btn").forEach(function(b){b.setAttribute("aria-expanded","false")});openId=null;if(opts.returnFocus&&lastBtn){try{lastBtn.focus()}catch(e){}}}
  function placePanel(btn,panel){panel.classList.remove("is-above");panel.style.left="50%";panel.style.right="auto";panel.style.transform="translateX(-50%)";var rect=btn.getBoundingClientRect();var spaceBelow=window.innerHeight-rect.bottom;if(spaceBelow<180&&rect.top>spaceBelow)panel.classList.add("is-above");var pad=12,pr=panel.getBoundingClientRect(),dx=0;if(pr.right>window.innerWidth-pad)dx=window.innerWidth-pad-pr.right;if(pr.left+dx<pad)dx=pad-pr.left;if(dx){panel.style.left="50%";panel.style.transform="translateX(calc(-50% + "+dx+"px))"}}
  function build(tip){var btn=document.createElement("button");btn.type="button";btn.className="c3i-tip-btn";btn.setAttribute("aria-expanded","false");btn.setAttribute("aria-controls","c3i-tip-panel-"+tip.id);btn.setAttribute("aria-label","Ask Odin: "+tip.label);var face=document.createElement("img");face.className="c3i-tip-btn__face";face.src="odin-mark.svg";face.alt="";face.width=32;face.height=32;face.decoding="async";face.setAttribute("aria-hidden","true");var ask=document.createElement("span");ask.className="c3i-tip-btn__ask";ask.textContent="Ask";ask.setAttribute("aria-hidden","true");btn.appendChild(face);btn.appendChild(ask);return btn}
  TIPS.forEach(function(tip){var el=document.querySelector(tip.anchor);if(!el)return;var wrap=document.createElement("span");wrap.className="c3i-tip-wrap";wrap.dataset.tipId=tip.id;var btn=build(tip);var panel=document.createElement("div");panel.id="c3i-tip-panel-"+tip.id;panel.className="c3i-tip-panel";panel.setAttribute("role","dialog");panel.setAttribute("aria-label",tip.title);panel.hidden=true;var x=document.createElement("button");x.type="button";x.className="c3i-tip-panel__x";x.setAttribute("aria-label","Close");x.innerHTML="&times;";var title=document.createElement("p");title.className="c3i-tip-panel__title";title.textContent=tip.title;var body=document.createElement("p");body.className="c3i-tip-panel__body";body.id="c3i-tip-desc-"+tip.id;body.textContent=tip.body;var ok=document.createElement("button");ok.type="button";ok.className="c3i-tip-panel__ok";ok.textContent="Got it";panel.setAttribute("aria-describedby",body.id);panel.appendChild(x);panel.appendChild(title);panel.appendChild(body);panel.appendChild(ok);function open(){closeAll();lastBtn=btn;panel.hidden=false;btn.setAttribute("aria-expanded","true");openId=tip.id;placePanel(btn,panel)}function dismiss(){markDismissed(tip.id);closeAll({returnFocus:true})}btn.addEventListener("click",function(e){e.preventDefault();e.stopPropagation();if(openId===tip.id){closeAll({returnFocus:true});return}open()});x.addEventListener("click",function(e){e.stopPropagation();dismiss()});ok.addEventListener("click",function(e){e.stopPropagation();dismiss()});panel.addEventListener("click",function(e){e.stopPropagation()});wrap.appendChild(btn);wrap.appendChild(panel);el.appendChild(wrap)});document.addEventListener("click",function(e){if(!e.target.closest(".c3i-tip-wrap")){if(openId)closeAll({returnFocus:true})}});document.addEventListener("keydown",function(e){if(e.key==="Escape"&&openId)closeAll({returnFocus:true})});window.addEventListener("resize",function(){if(!openId)return;var panel=document.getElementById("c3i-tip-panel-"+openId);var btn=document.querySelector('.c3i-tip-wrap[data-tip-id="'+openId+'"] .c3i-tip-btn');if(panel&&btn&&!panel.hidden)placePanel(btn,panel)},{passive:true})
})();
